config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'home#show'

  resource :home, only: [:show], controller: 'home'

  namespace :search do
    resources :items, only: [:index]

    resources :projects, only: [:index]

    resources :tags, only: [:index]

    resources :tag_facets, only: [:index] do
      collection do
        get 'children'
        get 'search'
      end
    end

    resources :project_facets, only: [:index] do
      collection do
        get 'children'
        get 'search'
      end
    end

    resources :workflow_facets, only: [:index] do
      collection do
        get 'children'
      end
    end

    resources :mimetype_facets, only: [:index] do
      collection do
        get 'children'
        get 'search'
      end
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller for the home page
class HomeController < SearchApplicationController
  def show
    @search_form = build_form(form_class: Search::Form)
    @items_search_form = build_form(form_class: Search::ItemForm)

    return if @search_form.query.blank?

    @projects_search_form = build_form(form_class: Search::Form)
    @tags_search_form = build_form(form_class: Search::Form)
  end
end

app/views/home/show.html.erb
<h1>Home Page</h1>

<%= render Search::FormComponent.new(search_form: @search_form, url: home_path, label: 'Search for items, tags or projects:') %>

<% if @projects_search_form %>
  <%= turbo_frame_tag 'projects-search', src: search_projects_path(@projects_search_form.attributes) do %>
    Loading projects...
  <% end %>
<% end %>

<% if @tags_search_form %>
  <%= turbo_frame_tag 'tags-search', src: search_tags_path(@tags_search_form.attributes) do %>
    Loading tags...
  <% end %>
<% end %>

<% if @items_search_form %>
  <%= turbo_frame_tag 'items-search', src: search_items_path(@items_search_form.attributes) do %>
    Loading items...
  <% end %>
<% end %>

<%= render Search::FacetsSectionComponent.new(search_form: @search_form) %>